//Created a variable and its an new json object 
//Language Translations
var language = {
    //here eneg is not required because the default lanaguage is English, but it is important to have because 
    //if somebody actually does try to contribute to our webite, 
    //They need to know what the langauge is that we are translating.
    eng: {
        Login: "Login",
        Home: "Home",
        About: "About Us",
        Drink: "Beverages",
        Chefs: "Chefs",
        Contact: "Contact Us",
        Content: "WELCOME TO FLYING DUTCHMAN..",
        Content2: "",
        Order: "Order Now",
        Reserve: "Reservations",
        AvalItmsTitle: "Available Items",
        SeleItmsTitle: "Selected Items",
        drinkMenuItems: ["Beer", "Spirits", "Wine", "Whiskey"],
        priceText: "Price",
        proceedCartText: "Cart",
        emptyCartText: "Unfortunately, Your Cart is Empty.",
        continueShopping: "Continue Shopping",
        paymentTitle: "Select Payment Type",
        cardPaymentText: "Card Payment",
        swishPaymentText: "Swish",
        cashPaymentText: "Cash",
        backCart:"To Order",
        buyNow:"To payment",
        undoText: "<- UNDO",
        redoText: "REDO ->",
        stockChangeConfirmButton: "Save Changes",
        stockItemDescription: ["Name of Item", "Amounts", "In Menu?", "Price"]
    },

    swe: {
        Login: "Logga In",
        Home: "Hem",
        About: "Om Oss",
        Drink: "Drycker",
        Chefs: "Kokar",
        Contact: "Kontakta oss",
        Content: "VÄLKOMMEN TILL FLYING DUTCHMAN..",
        Content2: "",
        Order: "Beställ nu",
        Reserve: "Reservationer",
        AvalItmsTitle: "Tillgängliga artiklar",
        SeleItmsTitle: "Valda objekt",
        drinkMenuItems: ["Öl", "Sprit", "Vin", "Whisky"],
        priceText: "Pris",
        proceedCartText: "Vagn",
        emptyCartText: "Tyvärr är din kundvagn tom.",
        continueShopping: "Fortsätt handla",
        paymentTitle: "Välj Betalningstyp",
        cardPaymentText: "Kortbetalning",
        swishPaymentText: "Swish",
        cashPaymentText: "Kontanter",
        backCart: "Att beställa",
        buyNow: "Till betalning",
        undoText: "<- ÅNGRA",
        redoText: "GÖRA OM ->",
        stockChangeConfirmButton: "Spara ändringar",
        stockItemDescription: ["Namn på objekt", "belopp", "i menyn?", "Pris"]
    }
};